### ISSUE TITLE
Broken Example

### ISSUE THREAD

**Issue by PhantomKnight287** [istornz/flutter_live_activities#104]
I cloned the repository and tried to run the application inside `example` folder. The app started but when I clicked on the button to start live activity, I get the error of `null check used on a null value`. Below is the image and stack trace of the error.

```bash
Launching lib/main.dart on iPhone 15 Pro Max in debug mode...
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
Xcode build done.                                           45.9s
Connecting to VM Service at ws://127.0.0.1:50966/6YrRKK_YtDk=/ws
Connected to the VM Service.
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      AppGroupsImageService.sendImageToAppGroups (package:live_activities/services/app_groups_image_service.dart:29:41)
app_groups_image_service.dart:29
<asynchronous suspension>
#1      LiveActivities.createActivity (package:live_activities/live_activities.dart:37:5)
live_activities.dart:37
<asynchronous suspension>
#2      _HomeState.build.<anonymous closure> (package:live_activities_example/main.dart:173:40)
main.dart:173
<asynchronous suspension>
```

![image](https://github.com/user-attachments/assets/9afb3ef8-5927-4252-addb-e1cfc21a2a32)

**Comment by istornz** [comment]
Thanks for raising an issue, I will check that ASAP

**Comment by istornz** [comment]
Hi, I tried on my side and I can't reproduce it. Maybe do you have a valid App Group registered? (check the following steps here : [https://github.com/istornz/flutter_live_activities?tab=readme-ov-file#-native](https://github.com/istornz/flutter_live_activities?tab=readme-ov-file#-native))

**Comment by PhantomKnight287** [comment]
Yes, I have a valid group id. 

![image](https://github.com/user-attachments/assets/0d4af178-7aa0-409b-9553-4e70585d7e70)

**Comment by istornz** [comment]
It seems the plugin can't access to your app group in this code :
`Directory? sharedDirectory =
      await FlutterAppGroupDirectory.getAppGroupDirectory(
    appGroupId!,
  );`

The `sharedDirectory` return null on your side, maybe an issue by configuring the app group? Do you have added AppGroup for both Runner and your widget extension?

**Comment by PhantomKnight287** [comment]
Yes it is configured for both Runner and Widget extension.
![image](https://github.com/user-attachments/assets/2af54cbf-62c3-4206-a0f0-129bf37243f6)
![image](https://github.com/user-attachments/assets/65ef0878-3039-41fb-98c3-381965fb6301)

**Comment by ahndwon** [comment]
have you fixed this??

**Comment by PhantomKnight287** [comment]
> have you fixed this?? or a workaround?

No
