### ISSUE TITLE
LiveActivityImageFromUrl doesn't work

### ISSUE THREAD

**Issue by RadwaAlaa** [istornz/flutter_live_activities#46]

**Comment by charlesRmajor** [comment]
This is the error message I'm seeing:
```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Unsupported operation: Infinity or NaN toInt
#0      double.toInt (dart:core-patch/double.dart)
#1      double.round (dart:core-patch/double.dart:193:34)
#2      AppGroupsImageService.sendImageToAppGroups (package:live_activities/services/app_groups_image_service.dart:65:72)
<asynchronous suspension>
#3      LiveActivities.createActivity (package:live_activities/live_activities.dart:32:5)
<asynchronous suspension>
```

**Comment by charlesRmajor** [comment]
Ah! I think it's only an issue if you're using the 'resizeFactor'. When I take that parameter out, it works.

**Comment by istornz** [comment]
Thanks for the explanation @charlesRmajor, Is it reproductible with any image links (can't test for now) or a specific link?

**Comment by aumb** [comment]
This is caused when using `LiveActivityImageFromUrl` with a resize factor < 1 because the compression package being used is unable to get the properties which leads to dividing by 0 on

```dart
(properties.height! * targetWidth / properties.width!).round(),
```

which yields infinity

PS the package being used for compression is discontinued
