### ISSUE TITLE
iOS Apps on Mac Availability

### ISSUE THREAD

**Issue by Igos19** [istornz/flutter_live_activities#98]
After upgrading flutter_live_activities to version 2.0.0, ios app crashes on Apple silicon Mac with error:
 Termination Reason: SIGNAL 6 Abort trap: 6. Triggered by Thread:  1
 On previous version of the flutter_live_activities everything works fine.

Thread 1 Crashed:
0   libsystem_kernel.dylib        	       0x18b052600 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x18b08af70 pthread_kill + 288
2   libsystem_c.dylib             	       0x18af97908 abort + 128
3   libswiftCore.dylib            	       0x19c061484 swift::fatalErrorv(unsigned int, char const*, char*) + 136
4   libswiftCore.dylib            	       0x19c0614a4 swift::fatalError(unsigned int, char const*, ...) + 32
5   libswiftCore.dylib            	       0x19c09d680 swift::ResolveAsSymbolicReference::operator()(swift::Demangle::__runtime::SymbolicReferenceKind, swift::Demangle::__runtime::Directness, int, void const*) + 672
6   libswiftCore.dylib            	       0x19c0d85f4 swift::Demangle::__runtime::Demangler::demangleSymbolicReference(unsigned char) + 292
7   libswiftCore.dylib            	       0x19c0d4514 swift::Demangle::__runtime::Demangler::demangleType(__swift::__runtime::llvm::StringRef, std::__1::function<swift::Demangle::__runtime::Node* (swift::Demangle::__runtime::SymbolicReferenceKind, swift::Demangle::__runtime::Directness, int, void const*)>) + 272
8   libswiftCore.dylib            	       0x19c0a6080 swift_getTypeByMangledNameImpl(swift::MetadataRequest, __swift::__runtime::llvm::StringRef, void const* const*, std::__1::function<void const* (unsigned int, unsigned int)>, std::__1::function<swift::TargetWitnessTable<swift::InProcess> const* (swift::TargetMetadata<swift::InProcess> const*, unsigned int)>) + 520
9   libswiftCore.dylib            	       0x19c09fd68 swift_getTypeByMangledName + 836
10  libswiftCore.dylib            	       0x19c0a01d0 swift_getTypeByMangledNameInContextImpl(char const*, unsigned long, swift::TargetContextDescriptor<swift::InProcess> const*, void const* const*) + 176
11  live_activities               	       0x100e6897c __swift_instantiateConcreteTypeFromMangledName + 56
12  live_activities               	       0x100e5c284 closure #1 in static SwiftLiveActivitiesPlugin.register(with:) + 68
13  live_activities               	       0x100e7000d partial apply for closure #1 in SwiftLiveActivitiesPlugin.getPushToStartToken() + 1
14  live_activities               	       0x100e670c1 specialized thunk for @escaping @isolated(any) @callee_guaranteed @async () -> (@out A) + 1
15  live_activities               	       0x100e6ea21 thunk for @escaping @isolated(any) @callee_guaranteed @async () -> (@out A)specialized partial apply + 1
16  libswift_Concurrency.dylib    	       0x264831035 completeTaskWithClosure(swift::AsyncContext*, swift::SwiftError*) + 1

**Comment by istornz** [comment]
Thanks for raising an issue, can you test again with the latest version?

**Comment by Igos19** [comment]
Tested with the 2.0.1, still crashed

**Comment by istornz** [comment]
Tried to create a macOS project inside the example & launch on macOS but It won't crash on MacBook Pro M2 Pro.
I just see some errors (normal).

Can you reproduce it on the example project? Do you launch the "macOS" target or "Mac Designed for iPad"?

```ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method init on channel live_activities)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
platform_channel.dart:332
<asynchronous suspension>
#1      MethodChannelLiveActivities.init (package:live_activities/live_activities_method_channel.dart:29:5)
live_activities_method_channel.dart:29
<asynchronous suspension>
2

════════ Exception caught by services library ══════════════════════════════════
The following MissingPluginException was thrown while activating platform stream on channel live_activities/activity_status:
MissingPluginException(No implementation found for method listen on channel live_activities/activity_status)

When the exception was thrown, this was the stack:
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
platform_channel.dart:332
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:676:9)
platform_channel.dart:676
<asynchronous suspension>
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by services library ══════════════════════════════════
MissingPluginException(No implementation found for method listen on channel live_activities/url_scheme)
════════════════════════════════════════════════════════════════════════════════
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PathNotFoundException: Creation failed, path = '/Users/dimitri.dessus/Library/Group Containers/group.dimitridessus.liveactivities/LiveActivitiesPictures' (OS Error: No such file or directory, errno = 2)
#0      _Directory.createSync (dart:io/directory_impl.dart:124:7)
directory_impl.dart:124
#1      AppGroupsImageService.sendImageToAppGroups (package:live_activities/services/app_groups_image_service.dart:33:25)
app_groups_image_service.dart:33
<asynchronous suspension>
#2      LiveActivities.createActivity (package:live_activities/live_activities.dart:37:5)
live_activities.dart:37
<asynchronous suspension>
#3      _HomeState.build.<anonymous closure> (package:live_activities_example/main.dart:177:25)
main.dart:177
<asynchronous suspension>
```

**Comment by Igos19** [comment]
I build ios (target) app and deploy it to test flight. Then launch the app on MacBook with  m1 processor.

**Comment by Igos19** [comment]
It is reproduced on the example project. 
<img width="1295" alt="image" src="https://github.com/user-attachments/assets/f2264c5a-c8d0-40d7-ab6f-c337c87d9d4f">

**Comment by tl0601** [comment]
I have the same issue. It's working for iPad but crashing for Mac Designed for iPad

**Comment by iouoiuo** [comment]
Any solution?

**Comment by Igos19** [comment]
There's no this bug on flutter 3.29.0
